export default {
  SET_USER_INFO: 'SET_USER_INFO',
  SET_CEREMONY_INFO: 'SET_CEREMONY_INFO',
  SET_GOAL_INFO: 'SET_GOAL_INFO',
  GOAL_INFO_UPDATE: 'GOAL_INFO_UPDATE',
  DELETE_GOAL_BY_DATE: 'DELETE_GOAL_BY_DATE',
  DELETE_TASK_BY_ID :'DELETE_TASK_BY_ID',
    GOAL_ALLINFO_UPDATE: 'GOAL_ALLINFO_UPDATE',
};
